//! In-browser (and Node) proving for the MaskedUSD circuits — NoirJS witness generation + bb.js
//! UltraHonk proving, configured to match the on-chain verifier exactly.
//!
//! The verifier was generated by the `bb` CLI with `--oracle_hash keccak`, which produces the **ZK**
//! Honk flavor (the generated contract is a "ZK Honk solidity verifier", ~226-field proof). bb.js must
//! therefore use `{ keccakZK: true }` (keccak oracle, ZK enabled) — plain `{ keccak: true }` sets
//! `disableZk: true` and yields a shorter non-ZK proof the deployed verifier rejects. bb.js must also
//! be the SAME version (pinned in package.json) or the proof/VK won't match. The whole point of this
//! module: a proof built here — on a phone, in a Farcaster webview — verifies against the deployed
//! Solidity verifier.

/// Proof options matching the deployed verifiers (ZK Honk, keccak oracle). Centralized so prove +
/// verify never drift apart, and so a future verifier-flavor change is a one-line edit.
const HONK_OPTS = { keccakZK: true } as const;

import { Noir } from "@noir-lang/noir_js";
import { Barretenberg, UltraHonkBackend } from "@aztec/bb.js";

/// A compiled Noir circuit (the `circuits/target/<name>.json` artifact).
export interface CompiledCircuit {
  bytecode: string;
  abi: unknown;
}

/// Inputs to a circuit, keyed by Noir parameter name. Values are decimal/hex strings or numbers/bigints
/// (NoirJS accepts these); arrays for array params. Render field elements with `toHex32` for safety.
export type CircuitInputs = Record<string, unknown>;

/// A generated proof, split exactly the way the on-chain verifier consumes it: the raw proof bytes
/// (pairing points live inside) and the logical public inputs as 32-byte hex words.
export interface HonkProof {
  proof: Uint8Array;
  publicInputs: string[];
}

/**
 * Generate an UltraHonk (ZK, keccak-oracle) proof for `circuit` with `inputs` — the flavor the
 * on-chain verifier accepts. NoirJS solves the witness; bb.js proves. `threads` defaults to 1
 * (portable; raise it where the platform exposes real worker threads).
 *
 * @returns `{ proof, publicInputs }` split the way the on-chain verifier consumes them.
 */
export async function generateHonkProof(
  circuit: CompiledCircuit,
  inputs: CircuitInputs,
  threads = 1,
): Promise<HonkProof> {
  const noir = new Noir(circuit as never);
  const { witness } = await noir.execute(inputs as never);

  const api = await Barretenberg.new({ threads });
  try {
    const backend = new UltraHonkBackend(circuit.bytecode, api);
    const { proof, publicInputs } = await backend.generateProof(witness, HONK_OPTS);
    return { proof, publicInputs };
  } finally {
    await api.destroy();
  }
}

/**
 * Verify a proof with bb.js — an off-chain sanity check before submitting. Uses the same keccak
 * oracle. On-chain verification via the Solidity verifier is the real gate.
 */
export async function verifyHonkProof(circuit: CompiledCircuit, proof: HonkProof, threads = 1): Promise<boolean> {
  const api = await Barretenberg.new({ threads });
  try {
    const backend = new UltraHonkBackend(circuit.bytecode, api);
    return await backend.verifyProof(proof, HONK_OPTS);
  } finally {
    await api.destroy();
  }
}
